# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'x:\PyQT_Tutorial\NotePad\NotePad.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 591)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout.addWidget(self.plainTextEdit, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menu_file = QtWidgets.QMenu(self.menubar)
        self.menu_file.setObjectName("menu_file")
        self.menu_edit = QtWidgets.QMenu(self.menubar)
        self.menu_edit.setObjectName("menu_edit")
        self.menu_form = QtWidgets.QMenu(self.menubar)
        self.menu_form.setObjectName("menu_form")
        self.menu_view = QtWidgets.QMenu(self.menubar)
        self.menu_view.setObjectName("menu_view")
        self.menu = QtWidgets.QMenu(self.menu_view)
        self.menu.setObjectName("menu")
        self.menu_help = QtWidgets.QMenu(self.menubar)
        self.menu_help.setObjectName("menu_help")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_open = QtWidgets.QAction(MainWindow)
        self.action_open.setObjectName("action_open")
        self.action_save = QtWidgets.QAction(MainWindow)
        self.action_save.setObjectName("action_save")
        self.action_saveAs = QtWidgets.QAction(MainWindow)
        self.action_saveAs.setObjectName("action_saveAs")
        self.action_close = QtWidgets.QAction(MainWindow)
        self.action_close.setObjectName("action_close")
        self.action_undo = QtWidgets.QAction(MainWindow)
        self.action_undo.setObjectName("action_undo")
        self.action_cut = QtWidgets.QAction(MainWindow)
        self.action_cut.setObjectName("action_cut")
        self.action_copy = QtWidgets.QAction(MainWindow)
        self.action_copy.setObjectName("action_copy")
        self.action_paste = QtWidgets.QAction(MainWindow)
        self.action_paste.setObjectName("action_paste")
        self.action_find = QtWidgets.QAction(MainWindow)
        self.action_find.setObjectName("action_find")
        self.action_next_find = QtWidgets.QAction(MainWindow)
        self.action_next_find.setObjectName("action_next_find")
        self.action_prev_find = QtWidgets.QAction(MainWindow)
        self.action_prev_find.setObjectName("action_prev_find")
        self.action_find_replace = QtWidgets.QAction(MainWindow)
        self.action_find_replace.setObjectName("action_find_replace")
        self.action_go = QtWidgets.QAction(MainWindow)
        self.action_go.setObjectName("action_go")
        self.action_all_select = QtWidgets.QAction(MainWindow)
        self.action_all_select.setObjectName("action_all_select")
        self.action_datetime = QtWidgets.QAction(MainWindow)
        self.action_datetime.setObjectName("action_datetime")
        self.action_wrap = QtWidgets.QAction(MainWindow)
        self.action_wrap.setObjectName("action_wrap")
        self.action_16 = QtWidgets.QAction(MainWindow)
        self.action_16.setObjectName("action_16")
        self.action_18 = QtWidgets.QAction(MainWindow)
        self.action_18.setCheckable(True)
        self.action_18.setObjectName("action_18")
        self.action_19 = QtWidgets.QAction(MainWindow)
        self.action_19.setObjectName("action_19")
        self.action_20 = QtWidgets.QAction(MainWindow)
        self.action_20.setObjectName("action_20")
        self.action_21 = QtWidgets.QAction(MainWindow)
        self.action_21.setObjectName("action_21")
        self.action_help = QtWidgets.QAction(MainWindow)
        self.action_help.setObjectName("action_help")
        self.action_23 = QtWidgets.QAction(MainWindow)
        self.action_23.setObjectName("action_23")
        self.action_Info = QtWidgets.QAction(MainWindow)
        self.action_Info.setObjectName("action_Info")
        self.menu_file.addAction(self.action_open)
        self.menu_file.addAction(self.action_save)
        self.menu_file.addAction(self.action_saveAs)
        self.menu_file.addAction(self.action_close)
        self.menu_edit.addAction(self.action_undo)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_cut)
        self.menu_edit.addAction(self.action_copy)
        self.menu_edit.addAction(self.action_paste)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_find)
        self.menu_edit.addAction(self.action_next_find)
        self.menu_edit.addAction(self.action_prev_find)
        self.menu_edit.addAction(self.action_find_replace)
        self.menu_edit.addAction(self.action_go)
        self.menu_edit.addSeparator()
        self.menu_edit.addAction(self.action_all_select)
        self.menu_edit.addAction(self.action_datetime)
        self.menu_form.addAction(self.action_wrap)
        self.menu_form.addAction(self.action_16)
        self.menu.addAction(self.action_19)
        self.menu.addAction(self.action_20)
        self.menu.addAction(self.action_21)
        self.menu_view.addAction(self.menu.menuAction())
        self.menu_view.addAction(self.action_18)
        self.menu_help.addAction(self.action_help)
        self.menu_help.addAction(self.action_23)
        self.menu_help.addSeparator()
        self.menu_help.addAction(self.action_Info)
        self.menubar.addAction(self.menu_file.menuAction())
        self.menubar.addAction(self.menu_edit.menuAction())
        self.menubar.addAction(self.menu_form.menuAction())
        self.menubar.addAction(self.menu_view.menuAction())
        self.menubar.addAction(self.menu_help.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "안녕나메모장"))
        self.menu_file.setTitle(_translate("MainWindow", "파일"))
        self.menu_edit.setTitle(_translate("MainWindow", "편집"))
        self.menu_form.setTitle(_translate("MainWindow", "서식"))
        self.menu_view.setTitle(_translate("MainWindow", "보기"))
        self.menu.setTitle(_translate("MainWindow", "확대하기/축소하기"))
        self.menu_help.setTitle(_translate("MainWindow", "도움말"))
        self.action_open.setText(_translate("MainWindow", "열기"))
        self.action_open.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.action_save.setText(_translate("MainWindow", "저장"))
        self.action_save.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.action_saveAs.setText(_translate("MainWindow", "다른 이름으로 저장"))
        self.action_saveAs.setShortcut(_translate("MainWindow", "Ctrl+Shift+S"))
        self.action_close.setText(_translate("MainWindow", "끝내기"))
        self.action_close.setShortcut(_translate("MainWindow", "Esc"))
        self.action_undo.setText(_translate("MainWindow", "실행취소"))
        self.action_undo.setShortcut(_translate("MainWindow", "Ctrl+Z"))
        self.action_cut.setText(_translate("MainWindow", "잘라내기"))
        self.action_cut.setShortcut(_translate("MainWindow", "Ctrl+X"))
        self.action_copy.setText(_translate("MainWindow", "복사"))
        self.action_copy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.action_paste.setText(_translate("MainWindow", "붙여넣기"))
        self.action_paste.setShortcut(_translate("MainWindow", "Ctrl+V"))
        self.action_find.setText(_translate("MainWindow", "찾기"))
        self.action_find.setShortcut(_translate("MainWindow", "Ctrl+F"))
        self.action_next_find.setText(_translate("MainWindow", "다음 찾기"))
        self.action_next_find.setShortcut(_translate("MainWindow", "F3"))
        self.action_prev_find.setText(_translate("MainWindow", "이전 찾기"))
        self.action_prev_find.setShortcut(_translate("MainWindow", "Shift+F3"))
        self.action_find_replace.setText(_translate("MainWindow", "바꾸기"))
        self.action_find_replace.setShortcut(_translate("MainWindow", "Ctrl+H"))
        self.action_go.setText(_translate("MainWindow", "이동"))
        self.action_go.setShortcut(_translate("MainWindow", "Ctrl+G"))
        self.action_all_select.setText(_translate("MainWindow", "모두 선택"))
        self.action_all_select.setShortcut(_translate("MainWindow", "Ctrl+A"))
        self.action_datetime.setText(_translate("MainWindow", "시간/날짜"))
        self.action_datetime.setShortcut(_translate("MainWindow", "F5"))
        self.action_wrap.setText(_translate("MainWindow", "자동 줄 바꿈"))
        self.action_16.setText(_translate("MainWindow", "글꼴"))
        self.action_18.setText(_translate("MainWindow", "상태 표시줄"))
        self.action_19.setText(_translate("MainWindow", "확대"))
        self.action_19.setShortcut(_translate("MainWindow", "Ctrl+Shift+="))
        self.action_20.setText(_translate("MainWindow", "축소"))
        self.action_20.setShortcut(_translate("MainWindow", "Ctrl+-"))
        self.action_21.setText(_translate("MainWindow", "확대하기/축소하기 기본값 복원"))
        self.action_help.setText(_translate("MainWindow", "도움말 보기"))
        self.action_23.setText(_translate("MainWindow", "피드백 보내기"))
        self.action_Info.setText(_translate("MainWindow", "메모장 정보"))

